doctrine:
  #
  # Default Entity Manager
  #
  default: default

  #
  # List Of Entity Managers
  #
  orm:
    default:
      connection: sqlite_local
      paths: '%path.app%/Entity'

  #
  # List Of Database Connections
  #
  connections:
    sqlite_local:
      driver: pdo_sqlite
      path: '%path.root%/resources/database/db.sqlite'

