doctrine:
  pool:
    # Max available connections:
    #
    # <= 0: Unlimited connections.
    # >= 1: The specified number of connections.
    max: 1024

    # Connections establishment algorithm:
    #
    # - single_read_uniq_write: General connection for reading, separate for
    #                           writing for each client (request).
    # - uniq:                   Separate for each client (request).
    # - single:                 Use one general connection.
    #
    # Modes other than "single" make sense when working
    # in an event loop instead of FCGI mode.
    poller: single_read_uniq_write

  #
  # List of repository interface bindings
  #
  repositories:
    App\Entity\Article: App\Entity\Article\ArticleRepositoryInterface

  #
  # Default Entity Manager
  #
  default: default

  #
  # List Of Entity Managers
  #
  orm:
    default:
      connection: sqlite_local
      paths: '%path.app%/Entity'

  #
  # List Of Database Connections
  #
  connections:
    sqlite_local:
      driver: pdo_sqlite
      path: '%path.root%/resources/database/db.sqlite'

